let words: string[] = [
    'CASA',
    'PERRO',
    'GATO',
    'SOL',
    'LUNA',
    'ÁRBOL',
    'AGUA',
    'MONTAÑA',
    'FLOR',
    'COCHE',
    'COMPUTADORA',
    'LIBRO',
    'AMOR',
    'ODIO',
    'FELICIDAD',
    'TRISTEZA',
    'TIERRA',
    'CIELO',
    'MAR',
    'AIRE',
    'FUEGO',
    'AMIGO',
    'FAMILIA',
    'CIUDAD',
    'VIAJE',
    'TRABAJO',
    'ESCUELA',
    'MÚSICA',
    'ARTE',
    'PALABRA',
    'COLOR',
    'COMIDA',
    'SUEÑO',
    'RÍO',
    'PUENTE',
    'PUERTA',
    'VENTANA',
    'RELOJ',
    'TIEMPO',
    'ESPACIO',
    'SILENCIO',
    'RISA',
    'LLANTO',
    'JUEGO',
    'DEPORT',
    'CALLE',
    'HISTORIA',
    'CULTURA',
    'NATURALEZA',
    'ASTRONOMÍA',
    'EXTRAVAGANTE',
    'INEXORABLE',
    'OBSEQUIOSO',
    'FORTUITO',
    'QUINTAESNCIA',
    'XILÓFONO',
    'YÓQUEY',
    'ELOCUENTE',
    'ANACRONISMO',
    'QUIOSCOSCO',
    'CIRCUNLOQUIO',
    'DÉFICIT',
    'EFIMERO',
    'JUBILO',
    'OBVIO',
    'AVIDO',
    'CEFIRO',
    'OSCURO',
    'EXAMENES',
    'ANTECEDENTE',
    'OQUEDAD',
    'EQUILIBRIO',
    'ULTRAJE',
    'XERÓFILO',
    'ADQUISICIÓN',
    'QUIMÉRICO',
    'UMBRAL',
];


export function getRandomWord(){

    const randomIndex = ( Math.floor (Math.random() *words.length) );

    return words [randomIndex];
}